// DO NOT MODIFY THIS FILE!
// The contents of this file are generated by build.rs automatically.
// Any changes you make here WILL be overwritten.
#![allow(clippy::unreadable_literal)]
#![cfg_attr(rustfmt, rustfmt_skip)]
use std::ops::Index;
use crate::{Color, Flavor, Hsl, Palette, Rgb};
/// All of the colors for a particular flavor of Catppuccin.
/// Obtained via [`Flavor::colors`].
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct FlavorColors {
    /// <div style="display: inline-block; background-color:hsl(10.799999999999995 58% 66%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(10.2857142857143 57% 88%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(9.999999999999964 57% 89%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(9.599999999999968 55% 91%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub rosewater: Color,
    /// <div style="display: inline-block; background-color:hsl(0 59% 66%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(0 58% 83%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(0 58% 85%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(0 58% 87%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub flamingo: Color,
    /// <div style="display: inline-block; background-color:hsl(316.0344827586207 73% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(316 73% 83%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(316.0714285714286 73% 85%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(316.4705882352941 71% 86%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub pink: Color,
    /// <div style="display: inline-block; background-color:hsl(266.0439560439561 85% 58%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(276.66666666666663 59% 76%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(266.51162790697674 82% 79%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(267.4074074074074 83% 80%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub mauve: Color,
    /// <div style="display: inline-block; background-color:hsl(347.0769230769231 86% 44%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(358.8118811881188 67% 70%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(351.1764705882353 73% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(343.2692307692308 81% 74%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub red: Color,
    /// <div style="display: inline-block; background-color:hsl(354.78260869565213 76% 58%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(357.77777777777777 65% 75%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(355.05882352941177 71% 76%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(350.4 65% 77%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub maroon: Color,
    /// <div style="display: inline-block; background-color:hsl(21.975308641975307 99% 51%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(20.33057851239669 79% 70%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(21.355932203389827 85% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(22.95652173913043 92% 75%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub peach: Color,
    /// <div style="display: inline-block; background-color:hsl(34.948453608247426 76% 49%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(39.52941176470588 62% 73%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(40.253164556962034 69% 77%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(41.35135135135135 86% 83%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub yellow: Color,
    /// <div style="display: inline-block; background-color:hsl(109.23076923076924 57% 39%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(95.83333333333331 43% 67%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(105.21739130434784 48% 71%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(115.45454545454544 54% 76%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub green: Color,
    /// <div style="display: inline-block; background-color:hsl(183.23076923076923 73% 34%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(171.5492957746479 39% 64%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(171.08108108108107 46% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(170.00000000000003 57% 73%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub teal: Color,
    /// <div style="display: inline-block; background-color:hsl(197.0666666666667 96% 45%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(189.0909090909091 47% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(188.780487804878 59% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(189.18367346938777 71% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub sky: Color,
    /// <div style="display: inline-block; background-color:hsl(188.85906040268455 69% 41%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(198.62068965517244 55% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(198.64077669902912 65% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(198.5 75% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub sapphire: Color,
    /// <div style="display: inline-block; background-color:hsl(219.90697674418607 91% 53%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(221.6326530612245 74% 74%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(220.188679245283 82% 74%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(217.1681415929203 91% 75%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub blue: Color,
    /// <div style="display: inline-block; background-color:hsl(230.93525179856115 97% 71%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(238.9090909090909 66% 83%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(234.46153846153848 82% 84%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(231.89189189189187 97% 85%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub lavender: Color,
    /// <div style="display: inline-block; background-color:hsl(233.79310344827587 16% 35%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.2340425531915 70% 86%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.4418604651163 68% 87%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(226.15384615384616 63% 88%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub text: Color,
    /// <div style="display: inline-block; background-color:hsl(233.33333333333337 12% 41%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(226.66666666666669 43% 79%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228 39% 80%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(226.66666666666669 35% 80%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub subtext1: Color,
    /// <div style="display: inline-block; background-color:hsl(232.8 10% 47%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228.2926829268293 29% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.36842105263156 26% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.6470588235294 23% 71%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub subtext0: Color,
    /// <div style="display: inline-block; background-color:hsl(232.17391304347825 9% 53%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.69230769230768 22% 65%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228.33333333333331 20% 64%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228.3870967741935 16% 63%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub overlay2: Color,
    /// <div style="display: inline-block; background-color:hsl(231.42857142857144 10% 59%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(226.66666666666669 16% 58%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.6470588235294 15% 56%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.65517241379308 12% 55%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub overlay1: Color,
    /// <div style="display: inline-block; background-color:hsl(228.00000000000003 11% 65%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.0909090909091 13% 51%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.32258064516128 12% 49%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.7692307692308 10% 47%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub overlay0: Color,
    /// <div style="display: inline-block; background-color:hsl(226.6666666666667 12% 70%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228.00000000000003 13% 44%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.65517241379308 13% 41%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(232.5 12% 39%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub surface2: Color,
    /// <div style="display: inline-block; background-color:hsl(225.00000000000003 13% 76%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.1428571428571 14% 37%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(231.11111111111111 15% 33%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(234.2857142857143 13% 31%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub surface1: Color,
    /// <div style="display: inline-block; background-color:hsl(222.85714285714292 15% 82%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.00000000000003 15% 30%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.4 18% 26%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(236.84210526315792 16% 22%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub surface0: Color,
    /// <div style="display: inline-block; background-color:hsl(220.00000000000009 23% 94%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.0909090909091 18% 23%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(231.8181818181818 23% 18%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(240 21% 14%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub base: Color,
    /// <div style="display: inline-block; background-color:hsl(220.00000000000009 21% 91%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.52631578947367 18% 19%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(233.33333333333337 23% 15%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(240 21% 11%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub mantle: Color,
    /// <div style="display: inline-block; background-color:hsl(220.00000000000009 20% 88%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.4117647058824 19% 17%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(235.71428571428572 22% 12%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(240 22% 8%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    pub crust: Color,
}
impl FlavorColors {
    /// Get an array of the colors in the flavor.
    #[must_use]
    pub const fn all_colors(&'static self) -> [&'static Color; 26] {
        [
            &self.rosewater,
            &self.flamingo,
            &self.pink,
            &self.mauve,
            &self.red,
            &self.maroon,
            &self.peach,
            &self.yellow,
            &self.green,
            &self.teal,
            &self.sky,
            &self.sapphire,
            &self.blue,
            &self.lavender,
            &self.text,
            &self.subtext1,
            &self.subtext0,
            &self.overlay2,
            &self.overlay1,
            &self.overlay0,
            &self.surface2,
            &self.surface1,
            &self.surface0,
            &self.base,
            &self.mantle,
            &self.crust,
        ]
    }
}
/// Enum of all named Catppuccin colors. Can be used to index into a [`FlavorColors`].
pub enum ColorName {
    /// <div style="display: inline-block; background-color:hsl(10.799999999999995 58% 66%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(10.2857142857143 57% 88%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(9.999999999999964 57% 89%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(9.599999999999968 55% 91%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Rosewater,
    /// <div style="display: inline-block; background-color:hsl(0 59% 66%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(0 58% 83%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(0 58% 85%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(0 58% 87%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Flamingo,
    /// <div style="display: inline-block; background-color:hsl(316.0344827586207 73% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(316 73% 83%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(316.0714285714286 73% 85%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(316.4705882352941 71% 86%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Pink,
    /// <div style="display: inline-block; background-color:hsl(266.0439560439561 85% 58%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(276.66666666666663 59% 76%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(266.51162790697674 82% 79%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(267.4074074074074 83% 80%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Mauve,
    /// <div style="display: inline-block; background-color:hsl(347.0769230769231 86% 44%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(358.8118811881188 67% 70%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(351.1764705882353 73% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(343.2692307692308 81% 74%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Red,
    /// <div style="display: inline-block; background-color:hsl(354.78260869565213 76% 58%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(357.77777777777777 65% 75%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(355.05882352941177 71% 76%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(350.4 65% 77%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Maroon,
    /// <div style="display: inline-block; background-color:hsl(21.975308641975307 99% 51%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(20.33057851239669 79% 70%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(21.355932203389827 85% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(22.95652173913043 92% 75%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Peach,
    /// <div style="display: inline-block; background-color:hsl(34.948453608247426 76% 49%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(39.52941176470588 62% 73%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(40.253164556962034 69% 77%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(41.35135135135135 86% 83%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Yellow,
    /// <div style="display: inline-block; background-color:hsl(109.23076923076924 57% 39%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(95.83333333333331 43% 67%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(105.21739130434784 48% 71%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(115.45454545454544 54% 76%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Green,
    /// <div style="display: inline-block; background-color:hsl(183.23076923076923 73% 34%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(171.5492957746479 39% 64%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(171.08108108108107 46% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(170.00000000000003 57% 73%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Teal,
    /// <div style="display: inline-block; background-color:hsl(197.0666666666667 96% 45%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(189.0909090909091 47% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(188.780487804878 59% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(189.18367346938777 71% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Sky,
    /// <div style="display: inline-block; background-color:hsl(188.85906040268455 69% 41%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(198.62068965517244 55% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(198.64077669902912 65% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(198.5 75% 69%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Sapphire,
    /// <div style="display: inline-block; background-color:hsl(219.90697674418607 91% 53%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(221.6326530612245 74% 74%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(220.188679245283 82% 74%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(217.1681415929203 91% 75%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Blue,
    /// <div style="display: inline-block; background-color:hsl(230.93525179856115 97% 71%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(238.9090909090909 66% 83%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(234.46153846153848 82% 84%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(231.89189189189187 97% 85%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Lavender,
    /// <div style="display: inline-block; background-color:hsl(233.79310344827587 16% 35%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.2340425531915 70% 86%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.4418604651163 68% 87%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(226.15384615384616 63% 88%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Text,
    /// <div style="display: inline-block; background-color:hsl(233.33333333333337 12% 41%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(226.66666666666669 43% 79%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228 39% 80%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(226.66666666666669 35% 80%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Subtext1,
    /// <div style="display: inline-block; background-color:hsl(232.8 10% 47%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228.2926829268293 29% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.36842105263156 26% 72%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.6470588235294 23% 71%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Subtext0,
    /// <div style="display: inline-block; background-color:hsl(232.17391304347825 9% 53%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.69230769230768 22% 65%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228.33333333333331 20% 64%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228.3870967741935 16% 63%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Overlay2,
    /// <div style="display: inline-block; background-color:hsl(231.42857142857144 10% 59%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(226.66666666666669 16% 58%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.6470588235294 15% 56%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.65517241379308 12% 55%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Overlay1,
    /// <div style="display: inline-block; background-color:hsl(228.00000000000003 11% 65%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.0909090909091 13% 51%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.32258064516128 12% 49%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.7692307692308 10% 47%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Overlay0,
    /// <div style="display: inline-block; background-color:hsl(226.6666666666667 12% 70%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(228.00000000000003 13% 44%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.65517241379308 13% 41%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(232.5 12% 39%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Surface2,
    /// <div style="display: inline-block; background-color:hsl(225.00000000000003 13% 76%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(227.1428571428571 14% 37%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(231.11111111111111 15% 33%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(234.2857142857143 13% 31%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Surface1,
    /// <div style="display: inline-block; background-color:hsl(222.85714285714292 15% 82%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.00000000000003 15% 30%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.4 18% 26%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(236.84210526315792 16% 22%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Surface0,
    /// <div style="display: inline-block; background-color:hsl(220.00000000000009 23% 94%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.0909090909091 18% 23%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(231.8181818181818 23% 18%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(240 21% 14%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Base,
    /// <div style="display: inline-block; background-color:hsl(220.00000000000009 21% 91%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(230.52631578947367 18% 19%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(233.33333333333337 23% 15%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(240 21% 11%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Mantle,
    /// <div style="display: inline-block; background-color:hsl(220.00000000000009 20% 88%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(229.4117647058824 19% 17%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(235.71428571428572 22% 12%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div><div style="display: inline-block; background-color:hsl(240 22% 8%); width: 10px; padding: 10px; margin: 0 2px 0; border: 1px solid #1e1e2e; border-radius: 10px"></div>
    Crust,
}
impl Index<ColorName> for FlavorColors {
    type Output = Color;

    fn index(&self, index: ColorName) -> &Self::Output {
        match index {
            ColorName::Rosewater => &self.rosewater,
            ColorName::Flamingo => &self.flamingo,
            ColorName::Pink => &self.pink,
            ColorName::Mauve => &self.mauve,
            ColorName::Red => &self.red,
            ColorName::Maroon => &self.maroon,
            ColorName::Peach => &self.peach,
            ColorName::Yellow => &self.yellow,
            ColorName::Green => &self.green,
            ColorName::Teal => &self.teal,
            ColorName::Sky => &self.sky,
            ColorName::Sapphire => &self.sapphire,
            ColorName::Blue => &self.blue,
            ColorName::Lavender => &self.lavender,
            ColorName::Text => &self.text,
            ColorName::Subtext1 => &self.subtext1,
            ColorName::Subtext0 => &self.subtext0,
            ColorName::Overlay2 => &self.overlay2,
            ColorName::Overlay1 => &self.overlay1,
            ColorName::Overlay0 => &self.overlay0,
            ColorName::Surface2 => &self.surface2,
            ColorName::Surface1 => &self.surface1,
            ColorName::Surface0 => &self.surface0,
            ColorName::Base => &self.base,
            ColorName::Mantle => &self.mantle,
            ColorName::Crust => &self.crust,
        }
    }
}
/// The Catppuccin palette. This constant will generally be your entrypoint
/// into using the crate.
pub const PALETTE: Palette = Palette {
    latte: Flavor {
        name: "Latte",
        dark: false,
        colors: FlavorColors {
            rosewater: Color {
                name: "rosewater",
                accent: true,
                hex: "#dc8a78",
                rgb: Rgb { r: 220, g: 138, b: 120 },
                hsl: Hsl { h: 10.799999999999995, s: 0.5882352941176472, l: 0.6666666666666667 },
            },
            flamingo: Color {
                name: "flamingo",
                accent: true,
                hex: "#dd7878",
                rgb: Rgb { r: 221, g: 120, b: 120 },
                hsl: Hsl { h: 0.0, s: 0.5976331360946746, l: 0.6686274509803922 },
            },
            pink: Color {
                name: "pink",
                accent: true,
                hex: "#ea76cb",
                rgb: Rgb { r: 234, g: 118, b: 203 },
                hsl: Hsl { h: 316.0344827586207, s: 0.7341772151898731, l: 0.6901960784313725 },
            },
            mauve: Color {
                name: "mauve",
                accent: true,
                hex: "#8839ef",
                rgb: Rgb { r: 136, g: 57, b: 239 },
                hsl: Hsl { h: 266.0439560439561, s: 0.8504672897196262, l: 0.5803921568627451 },
            },
            red: Color {
                name: "red",
                accent: true,
                hex: "#d20f39",
                rgb: Rgb { r: 210, g: 15, b: 57 },
                hsl: Hsl { h: 347.0769230769231, s: 0.8666666666666666, l: 0.4411764705882353 },
            },
            maroon: Color {
                name: "maroon",
                accent: true,
                hex: "#e64553",
                rgb: Rgb { r: 230, g: 69, b: 83 },
                hsl: Hsl { h: 354.78260869565213, s: 0.76303317535545, l: 0.5862745098039216 },
            },
            peach: Color {
                name: "peach",
                accent: true,
                hex: "#fe640b",
                rgb: Rgb { r: 254, g: 100, b: 11 },
                hsl: Hsl { h: 21.975308641975307, s: 0.9918367346938776, l: 0.5196078431372549 },
            },
            yellow: Color {
                name: "yellow",
                accent: true,
                hex: "#df8e1d",
                rgb: Rgb { r: 223, g: 142, b: 29 },
                hsl: Hsl { h: 34.948453608247426, s: 0.7698412698412698, l: 0.4941176470588235 },
            },
            green: Color {
                name: "green",
                accent: true,
                hex: "#40a02b",
                rgb: Rgb { r: 64, g: 160, b: 43 },
                hsl: Hsl { h: 109.23076923076924, s: 0.5763546798029556, l: 0.39803921568627454 },
            },
            teal: Color {
                name: "teal",
                accent: true,
                hex: "#179299",
                rgb: Rgb { r: 23, g: 146, b: 153 },
                hsl: Hsl { h: 183.23076923076923, s: 0.7386363636363636, l: 0.34509803921568627 },
            },
            sky: Color {
                name: "sky",
                accent: true,
                hex: "#04a5e5",
                rgb: Rgb { r: 4, g: 165, b: 229 },
                hsl: Hsl { h: 197.0666666666667, s: 0.965665236051502, l: 0.45686274509803926 },
            },
            sapphire: Color {
                name: "sapphire",
                accent: true,
                hex: "#209fb5",
                rgb: Rgb { r: 32, g: 159, b: 181 },
                hsl: Hsl { h: 188.85906040268455, s: 0.6995305164319249, l: 0.4176470588235294 },
            },
            blue: Color {
                name: "blue",
                accent: true,
                hex: "#1e66f5",
                rgb: Rgb { r: 30, g: 102, b: 245 },
                hsl: Hsl { h: 219.90697674418607, s: 0.9148936170212768, l: 0.5392156862745098 },
            },
            lavender: Color {
                name: "lavender",
                accent: true,
                hex: "#7287fd",
                rgb: Rgb { r: 114, g: 135, b: 253 },
                hsl: Hsl { h: 230.93525179856115, s: 0.972027972027972, l: 0.7196078431372549 },
            },
            text: Color {
                name: "text",
                accent: false,
                hex: "#4c4f69",
                rgb: Rgb { r: 76, g: 79, b: 105 },
                hsl: Hsl { h: 233.79310344827587, s: 0.16022099447513813, l: 0.3549019607843137 },
            },
            subtext1: Color {
                name: "subtext1",
                accent: false,
                hex: "#5c5f77",
                rgb: Rgb { r: 92, g: 95, b: 119 },
                hsl: Hsl { h: 233.33333333333337, s: 0.1279620853080569, l: 0.4137254901960784 },
            },
            subtext0: Color {
                name: "subtext0",
                accent: false,
                hex: "#6c6f85",
                rgb: Rgb { r: 108, g: 111, b: 133 },
                hsl: Hsl { h: 232.8, s: 0.10373443983402494, l: 0.4725490196078431 },
            },
            overlay2: Color {
                name: "overlay2",
                accent: false,
                hex: "#7c7f93",
                rgb: Rgb { r: 124, g: 127, b: 147 },
                hsl: Hsl { h: 232.17391304347825, s: 0.09623430962343092, l: 0.5313725490196078 },
            },
            overlay1: Color {
                name: "overlay1",
                accent: false,
                hex: "#8c8fa1",
                rgb: Rgb { r: 140, g: 143, b: 161 },
                hsl: Hsl { h: 231.42857142857144, s: 0.10047846889952144, l: 0.5901960784313726 },
            },
            overlay0: Color {
                name: "overlay0",
                accent: false,
                hex: "#9ca0b0",
                rgb: Rgb { r: 156, g: 160, b: 176 },
                hsl: Hsl { h: 228.00000000000003, s: 0.11235955056179768, l: 0.6509803921568628 },
            },
            surface2: Color {
                name: "surface2",
                accent: false,
                hex: "#acb0be",
                rgb: Rgb { r: 172, g: 176, b: 190 },
                hsl: Hsl { h: 226.6666666666667, s: 0.1216216216216216, l: 0.7098039215686275 },
            },
            surface1: Color {
                name: "surface1",
                accent: false,
                hex: "#bcc0cc",
                rgb: Rgb { r: 188, g: 192, b: 204 },
                hsl: Hsl { h: 225.00000000000003, s: 0.13559322033898308, l: 0.7686274509803922 },
            },
            surface0: Color {
                name: "surface0",
                accent: false,
                hex: "#ccd0da",
                rgb: Rgb { r: 204, g: 208, b: 218 },
                hsl: Hsl { h: 222.85714285714292, s: 0.1590909090909089, l: 0.8274509803921568 },
            },
            base: Color {
                name: "base",
                accent: false,
                hex: "#eff1f5",
                rgb: Rgb { r: 239, g: 241, b: 245 },
                hsl: Hsl { h: 220.00000000000009, s: 0.23076923076923136, l: 0.9490196078431372 },
            },
            mantle: Color {
                name: "mantle",
                accent: false,
                hex: "#e6e9ef",
                rgb: Rgb { r: 230, g: 233, b: 239 },
                hsl: Hsl { h: 220.00000000000009, s: 0.21951219512195116, l: 0.919607843137255 },
            },
            crust: Color {
                name: "crust",
                accent: false,
                hex: "#dce0e8",
                rgb: Rgb { r: 220, g: 224, b: 232 },
                hsl: Hsl { h: 220.00000000000009, s: 0.2068965517241376, l: 0.8862745098039215 },
            },
        },
    },
    frappe: Flavor {
        name: "Frappé",
        dark: true,
        colors: FlavorColors {
            rosewater: Color {
                name: "rosewater",
                accent: true,
                hex: "#f2d5cf",
                rgb: Rgb { r: 242, g: 213, b: 207 },
                hsl: Hsl { h: 10.2857142857143, s: 0.5737704918032784, l: 0.8803921568627451 },
            },
            flamingo: Color {
                name: "flamingo",
                accent: true,
                hex: "#eebebe",
                rgb: Rgb { r: 238, g: 190, b: 190 },
                hsl: Hsl { h: 0.0, s: 0.5853658536585367, l: 0.8392156862745098 },
            },
            pink: Color {
                name: "pink",
                accent: true,
                hex: "#f4b8e4",
                rgb: Rgb { r: 244, g: 184, b: 228 },
                hsl: Hsl { h: 316.0, s: 0.7317073170731713, l: 0.8392156862745098 },
            },
            mauve: Color {
                name: "mauve",
                accent: true,
                hex: "#ca9ee6",
                rgb: Rgb { r: 202, g: 158, b: 230 },
                hsl: Hsl { h: 276.66666666666663, s: 0.5901639344262294, l: 0.7607843137254902 },
            },
            red: Color {
                name: "red",
                accent: true,
                hex: "#e78284",
                rgb: Rgb { r: 231, g: 130, b: 132 },
                hsl: Hsl { h: 358.8118811881188, s: 0.6778523489932885, l: 0.7078431372549019 },
            },
            maroon: Color {
                name: "maroon",
                accent: true,
                hex: "#ea999c",
                rgb: Rgb { r: 234, g: 153, b: 156 },
                hsl: Hsl { h: 357.77777777777777, s: 0.6585365853658534, l: 0.7588235294117647 },
            },
            peach: Color {
                name: "peach",
                accent: true,
                hex: "#ef9f76",
                rgb: Rgb { r: 239, g: 159, b: 118 },
                hsl: Hsl { h: 20.33057851239669, s: 0.7908496732026143, l: 0.7 },
            },
            yellow: Color {
                name: "yellow",
                accent: true,
                hex: "#e5c890",
                rgb: Rgb { r: 229, g: 200, b: 144 },
                hsl: Hsl { h: 39.52941176470588, s: 0.6204379562043796, l: 0.7313725490196079 },
            },
            green: Color {
                name: "green",
                accent: true,
                hex: "#a6d189",
                rgb: Rgb { r: 166, g: 209, b: 137 },
                hsl: Hsl { h: 95.83333333333331, s: 0.4390243902439024, l: 0.6784313725490196 },
            },
            teal: Color {
                name: "teal",
                accent: true,
                hex: "#81c8be",
                rgb: Rgb { r: 129, g: 200, b: 190 },
                hsl: Hsl { h: 171.5492957746479, s: 0.3922651933701657, l: 0.6450980392156862 },
            },
            sky: Color {
                name: "sky",
                accent: true,
                hex: "#99d1db",
                rgb: Rgb { r: 153, g: 209, b: 219 },
                hsl: Hsl { h: 189.0909090909091, s: 0.47826086956521735, l: 0.7294117647058823 },
            },
            sapphire: Color {
                name: "sapphire",
                accent: true,
                hex: "#85c1dc",
                rgb: Rgb { r: 133, g: 193, b: 220 },
                hsl: Hsl { h: 198.62068965517244, s: 0.5541401273885351, l: 0.692156862745098 },
            },
            blue: Color {
                name: "blue",
                accent: true,
                hex: "#8caaee",
                rgb: Rgb { r: 140, g: 170, b: 238 },
                hsl: Hsl { h: 221.6326530612245, s: 0.7424242424242424, l: 0.7411764705882353 },
            },
            lavender: Color {
                name: "lavender",
                accent: true,
                hex: "#babbf1",
                rgb: Rgb { r: 186, g: 187, b: 241 },
                hsl: Hsl { h: 238.9090909090909, s: 0.6626506024096385, l: 0.8372549019607842 },
            },
            text: Color {
                name: "text",
                accent: false,
                hex: "#c6d0f5",
                rgb: Rgb { r: 198, g: 208, b: 245 },
                hsl: Hsl { h: 227.2340425531915, s: 0.7014925373134333, l: 0.8686274509803922 },
            },
            subtext1: Color {
                name: "subtext1",
                accent: false,
                hex: "#b5bfe2",
                rgb: Rgb { r: 181, g: 191, b: 226 },
                hsl: Hsl { h: 226.66666666666669, s: 0.43689320388349495, l: 0.7980392156862746 },
            },
            subtext0: Color {
                name: "subtext0",
                accent: false,
                hex: "#a5adce",
                rgb: Rgb { r: 165, g: 173, b: 206 },
                hsl: Hsl { h: 228.2926829268293, s: 0.2949640287769784, l: 0.7274509803921569 },
            },
            overlay2: Color {
                name: "overlay2",
                accent: false,
                hex: "#949cbb",
                rgb: Rgb { r: 148, g: 156, b: 187 },
                hsl: Hsl { h: 227.69230769230768, s: 0.22285714285714275, l: 0.6568627450980392 },
            },
            overlay1: Color {
                name: "overlay1",
                accent: false,
                hex: "#838ba7",
                rgb: Rgb { r: 131, g: 139, b: 167 },
                hsl: Hsl { h: 226.66666666666669, s: 0.16981132075471703, l: 0.584313725490196 },
            },
            overlay0: Color {
                name: "overlay0",
                accent: false,
                hex: "#737994",
                rgb: Rgb { r: 115, g: 121, b: 148 },
                hsl: Hsl { h: 229.0909090909091, s: 0.13360323886639683, l: 0.515686274509804 },
            },
            surface2: Color {
                name: "surface2",
                accent: false,
                hex: "#626880",
                rgb: Rgb { r: 98, g: 104, b: 128 },
                hsl: Hsl { h: 228.00000000000003, s: 0.1327433628318584, l: 0.4431372549019608 },
            },
            surface1: Color {
                name: "surface1",
                accent: false,
                hex: "#51576d",
                rgb: Rgb { r: 81, g: 87, b: 109 },
                hsl: Hsl { h: 227.1428571428571, s: 0.14736842105263157, l: 0.37254901960784315 },
            },
            surface0: Color {
                name: "surface0",
                accent: false,
                hex: "#414559",
                rgb: Rgb { r: 65, g: 69, b: 89 },
                hsl: Hsl { h: 230.00000000000003, s: 0.15584415584415584, l: 0.30196078431372547 },
            },
            base: Color {
                name: "base",
                accent: false,
                hex: "#303446",
                rgb: Rgb { r: 48, g: 52, b: 70 },
                hsl: Hsl { h: 229.0909090909091, s: 0.18644067796610175, l: 0.23137254901960785 },
            },
            mantle: Color {
                name: "mantle",
                accent: false,
                hex: "#292c3c",
                rgb: Rgb { r: 41, g: 44, b: 60 },
                hsl: Hsl { h: 230.52631578947367, s: 0.1881188118811881, l: 0.19803921568627453 },
            },
            crust: Color {
                name: "crust",
                accent: false,
                hex: "#232634",
                rgb: Rgb { r: 35, g: 38, b: 52 },
                hsl: Hsl { h: 229.4117647058824, s: 0.19540229885057467, l: 0.17058823529411765 },
            },
        },
    },
    macchiato: Flavor {
        name: "Macchiato",
        dark: true,
        colors: FlavorColors {
            rosewater: Color {
                name: "rosewater",
                accent: true,
                hex: "#f4dbd6",
                rgb: Rgb { r: 244, g: 219, b: 214 },
                hsl: Hsl { h: 9.999999999999964, s: 0.5769230769230775, l: 0.8980392156862745 },
            },
            flamingo: Color {
                name: "flamingo",
                accent: true,
                hex: "#f0c6c6",
                rgb: Rgb { r: 240, g: 198, b: 198 },
                hsl: Hsl { h: 0.0, s: 0.5833333333333333, l: 0.8588235294117648 },
            },
            pink: Color {
                name: "pink",
                accent: true,
                hex: "#f5bde6",
                rgb: Rgb { r: 245, g: 189, b: 230 },
                hsl: Hsl { h: 316.0714285714286, s: 0.7368421052631583, l: 0.8509803921568628 },
            },
            mauve: Color {
                name: "mauve",
                accent: true,
                hex: "#c6a0f6",
                rgb: Rgb { r: 198, g: 160, b: 246 },
                hsl: Hsl { h: 266.51162790697674, s: 0.8269230769230772, l: 0.7960784313725491 },
            },
            red: Color {
                name: "red",
                accent: true,
                hex: "#ed8796",
                rgb: Rgb { r: 237, g: 135, b: 150 },
                hsl: Hsl { h: 351.1764705882353, s: 0.7391304347826088, l: 0.7294117647058824 },
            },
            maroon: Color {
                name: "maroon",
                accent: true,
                hex: "#ee99a0",
                rgb: Rgb { r: 238, g: 153, b: 160 },
                hsl: Hsl { h: 355.05882352941177, s: 0.7142857142857143, l: 0.7666666666666666 },
            },
            peach: Color {
                name: "peach",
                accent: true,
                hex: "#f5a97f",
                rgb: Rgb { r: 245, g: 169, b: 127 },
                hsl: Hsl { h: 21.355932203389827, s: 0.8550724637681162, l: 0.7294117647058824 },
            },
            yellow: Color {
                name: "yellow",
                accent: true,
                hex: "#eed49f",
                rgb: Rgb { r: 238, g: 212, b: 159 },
                hsl: Hsl { h: 40.253164556962034, s: 0.6991150442477877, l: 0.7784313725490196 },
            },
            green: Color {
                name: "green",
                accent: true,
                hex: "#a6da95",
                rgb: Rgb { r: 166, g: 218, b: 149 },
                hsl: Hsl { h: 105.21739130434784, s: 0.4825174825174825, l: 0.7196078431372549 },
            },
            teal: Color {
                name: "teal",
                accent: true,
                hex: "#8bd5ca",
                rgb: Rgb { r: 139, g: 213, b: 202 },
                hsl: Hsl { h: 171.08108108108107, s: 0.46835443037974706, l: 0.6901960784313725 },
            },
            sky: Color {
                name: "sky",
                accent: true,
                hex: "#91d7e3",
                rgb: Rgb { r: 145, g: 215, b: 227 },
                hsl: Hsl { h: 188.780487804878, s: 0.5942028985507245, l: 0.7294117647058823 },
            },
            sapphire: Color {
                name: "sapphire",
                accent: true,
                hex: "#7dc4e4",
                rgb: Rgb { r: 125, g: 196, b: 228 },
                hsl: Hsl { h: 198.64077669902912, s: 0.6560509554140128, l: 0.692156862745098 },
            },
            blue: Color {
                name: "blue",
                accent: true,
                hex: "#8aadf4",
                rgb: Rgb { r: 138, g: 173, b: 244 },
                hsl: Hsl { h: 220.188679245283, s: 0.8281250000000003, l: 0.7490196078431373 },
            },
            lavender: Color {
                name: "lavender",
                accent: true,
                hex: "#b7bdf8",
                rgb: Rgb { r: 183, g: 189, b: 248 },
                hsl: Hsl { h: 234.46153846153848, s: 0.8227848101265824, l: 0.8450980392156863 },
            },
            text: Color {
                name: "text",
                accent: false,
                hex: "#cad3f5",
                rgb: Rgb { r: 202, g: 211, b: 245 },
                hsl: Hsl { h: 227.4418604651163, s: 0.6825396825396831, l: 0.8764705882352941 },
            },
            subtext1: Color {
                name: "subtext1",
                accent: false,
                hex: "#b8c0e0",
                rgb: Rgb { r: 184, g: 192, b: 224 },
                hsl: Hsl { h: 228.0, s: 0.392156862745098, l: 0.8 },
            },
            subtext0: Color {
                name: "subtext0",
                accent: false,
                hex: "#a5adcb",
                rgb: Rgb { r: 165, g: 173, b: 203 },
                hsl: Hsl { h: 227.36842105263156, s: 0.2676056338028167, l: 0.7215686274509804 },
            },
            overlay2: Color {
                name: "overlay2",
                accent: false,
                hex: "#939ab7",
                rgb: Rgb { r: 147, g: 154, b: 183 },
                hsl: Hsl { h: 228.33333333333331, s: 0.2000000000000001, l: 0.6470588235294117 },
            },
            overlay1: Color {
                name: "overlay1",
                accent: false,
                hex: "#8087a2",
                rgb: Rgb { r: 128, g: 135, b: 162 },
                hsl: Hsl { h: 227.6470588235294, s: 0.1545454545454545, l: 0.5686274509803921 },
            },
            overlay0: Color {
                name: "overlay0",
                accent: false,
                hex: "#6e738d",
                rgb: Rgb { r: 110, g: 115, b: 141 },
                hsl: Hsl { h: 230.32258064516128, s: 0.12350597609561752, l: 0.49215686274509807 },
            },
            surface2: Color {
                name: "surface2",
                accent: false,
                hex: "#5b6078",
                rgb: Rgb { r: 91, g: 96, b: 120 },
                hsl: Hsl { h: 229.65517241379308, s: 0.1374407582938389, l: 0.4137254901960784 },
            },
            surface1: Color {
                name: "surface1",
                accent: false,
                hex: "#494d64",
                rgb: Rgb { r: 73, g: 77, b: 100 },
                hsl: Hsl { h: 231.11111111111111, s: 0.15606936416184972, l: 0.3392156862745098 },
            },
            surface0: Color {
                name: "surface0",
                accent: false,
                hex: "#363a4f",
                rgb: Rgb { r: 54, g: 58, b: 79 },
                hsl: Hsl { h: 230.4, s: 0.1879699248120301, l: 0.2607843137254902 },
            },
            base: Color {
                name: "base",
                accent: false,
                hex: "#24273a",
                rgb: Rgb { r: 36, g: 39, b: 58 },
                hsl: Hsl { h: 231.8181818181818, s: 0.23404255319148937, l: 0.1843137254901961 },
            },
            mantle: Color {
                name: "mantle",
                accent: false,
                hex: "#1e2030",
                rgb: Rgb { r: 30, g: 32, b: 48 },
                hsl: Hsl { h: 233.33333333333337, s: 0.23076923076923075, l: 0.15294117647058825 },
            },
            crust: Color {
                name: "crust",
                accent: false,
                hex: "#181926",
                rgb: Rgb { r: 24, g: 25, b: 38 },
                hsl: Hsl { h: 235.71428571428572, s: 0.2258064516129032, l: 0.1215686274509804 },
            },
        },
    },
    mocha: Flavor {
        name: "Mocha",
        dark: true,
        colors: FlavorColors {
            rosewater: Color {
                name: "rosewater",
                accent: true,
                hex: "#f5e0dc",
                rgb: Rgb { r: 245, g: 224, b: 220 },
                hsl: Hsl { h: 9.599999999999968, s: 0.555555555555556, l: 0.911764705882353 },
            },
            flamingo: Color {
                name: "flamingo",
                accent: true,
                hex: "#f2cdcd",
                rgb: Rgb { r: 242, g: 205, b: 205 },
                hsl: Hsl { h: 0.0, s: 0.587301587301587, l: 0.8764705882352941 },
            },
            pink: Color {
                name: "pink",
                accent: true,
                hex: "#f5c2e7",
                rgb: Rgb { r: 245, g: 194, b: 231 },
                hsl: Hsl { h: 316.4705882352941, s: 0.7183098591549301, l: 0.8607843137254902 },
            },
            mauve: Color {
                name: "mauve",
                accent: true,
                hex: "#cba6f7",
                rgb: Rgb { r: 203, g: 166, b: 247 },
                hsl: Hsl { h: 267.4074074074074, s: 0.8350515463917528, l: 0.8098039215686275 },
            },
            red: Color {
                name: "red",
                accent: true,
                hex: "#f38ba8",
                rgb: Rgb { r: 243, g: 139, b: 168 },
                hsl: Hsl { h: 343.2692307692308, s: 0.8124999999999998, l: 0.7490196078431373 },
            },
            maroon: Color {
                name: "maroon",
                accent: true,
                hex: "#eba0ac",
                rgb: Rgb { r: 235, g: 160, b: 172 },
                hsl: Hsl { h: 350.4, s: 0.6521739130434779, l: 0.7745098039215685 },
            },
            peach: Color {
                name: "peach",
                accent: true,
                hex: "#fab387",
                rgb: Rgb { r: 250, g: 179, b: 135 },
                hsl: Hsl { h: 22.95652173913043, s: 0.92, l: 0.7549019607843137 },
            },
            yellow: Color {
                name: "yellow",
                accent: true,
                hex: "#f9e2af",
                rgb: Rgb { r: 249, g: 226, b: 175 },
                hsl: Hsl { h: 41.35135135135135, s: 0.8604651162790699, l: 0.8313725490196078 },
            },
            green: Color {
                name: "green",
                accent: true,
                hex: "#a6e3a1",
                rgb: Rgb { r: 166, g: 227, b: 161 },
                hsl: Hsl { h: 115.45454545454544, s: 0.5409836065573769, l: 0.7607843137254902 },
            },
            teal: Color {
                name: "teal",
                accent: true,
                hex: "#94e2d5",
                rgb: Rgb { r: 148, g: 226, b: 213 },
                hsl: Hsl { h: 170.00000000000003, s: 0.5735294117647057, l: 0.7333333333333334 },
            },
            sky: Color {
                name: "sky",
                accent: true,
                hex: "#89dceb",
                rgb: Rgb { r: 137, g: 220, b: 235 },
                hsl: Hsl { h: 189.18367346938777, s: 0.7101449275362316, l: 0.7294117647058823 },
            },
            sapphire: Color {
                name: "sapphire",
                accent: true,
                hex: "#74c7ec",
                rgb: Rgb { r: 116, g: 199, b: 236 },
                hsl: Hsl { h: 198.5, s: 0.759493670886076, l: 0.6901960784313725 },
            },
            blue: Color {
                name: "blue",
                accent: true,
                hex: "#89b4fa",
                rgb: Rgb { r: 137, g: 180, b: 250 },
                hsl: Hsl { h: 217.1681415929203, s: 0.91869918699187, l: 0.7588235294117647 },
            },
            lavender: Color {
                name: "lavender",
                accent: true,
                hex: "#b4befe",
                rgb: Rgb { r: 180, g: 190, b: 254 },
                hsl: Hsl { h: 231.89189189189187, s: 0.973684210526316, l: 0.8509803921568628 },
            },
            text: Color {
                name: "text",
                accent: false,
                hex: "#cdd6f4",
                rgb: Rgb { r: 205, g: 214, b: 244 },
                hsl: Hsl { h: 226.15384615384616, s: 0.6393442622950825, l: 0.8803921568627451 },
            },
            subtext1: Color {
                name: "subtext1",
                accent: false,
                hex: "#bac2de",
                rgb: Rgb { r: 186, g: 194, b: 222 },
                hsl: Hsl { h: 226.66666666666669, s: 0.35294117647058837, l: 0.8 },
            },
            subtext0: Color {
                name: "subtext0",
                accent: false,
                hex: "#a6adc8",
                rgb: Rgb { r: 166, g: 173, b: 200 },
                hsl: Hsl { h: 227.6470588235294, s: 0.23611111111111105, l: 0.7176470588235294 },
            },
            overlay2: Color {
                name: "overlay2",
                accent: false,
                hex: "#9399b2",
                rgb: Rgb { r: 147, g: 153, b: 178 },
                hsl: Hsl { h: 228.3870967741935, s: 0.16756756756756758, l: 0.6372549019607843 },
            },
            overlay1: Color {
                name: "overlay1",
                accent: false,
                hex: "#7f849c",
                rgb: Rgb { r: 127, g: 132, b: 156 },
                hsl: Hsl { h: 229.65517241379308, s: 0.12775330396475776, l: 0.5549019607843138 },
            },
            overlay0: Color {
                name: "overlay0",
                accent: false,
                hex: "#6c7086",
                rgb: Rgb { r: 108, g: 112, b: 134 },
                hsl: Hsl { h: 230.7692307692308, s: 0.10743801652892564, l: 0.4745098039215686 },
            },
            surface2: Color {
                name: "surface2",
                accent: false,
                hex: "#585b70",
                rgb: Rgb { r: 88, g: 91, b: 112 },
                hsl: Hsl { h: 232.5, s: 0.12, l: 0.392156862745098 },
            },
            surface1: Color {
                name: "surface1",
                accent: false,
                hex: "#45475a",
                rgb: Rgb { r: 69, g: 71, b: 90 },
                hsl: Hsl { h: 234.2857142857143, s: 0.13207547169811326, l: 0.31176470588235294 },
            },
            surface0: Color {
                name: "surface0",
                accent: false,
                hex: "#313244",
                rgb: Rgb { r: 49, g: 50, b: 68 },
                hsl: Hsl { h: 236.84210526315792, s: 0.16239316239316234, l: 0.22941176470588237 },
            },
            base: Color {
                name: "base",
                accent: false,
                hex: "#1e1e2e",
                rgb: Rgb { r: 30, g: 30, b: 46 },
                hsl: Hsl { h: 240.0, s: 0.21052631578947367, l: 0.14901960784313725 },
            },
            mantle: Color {
                name: "mantle",
                accent: false,
                hex: "#181825",
                rgb: Rgb { r: 24, g: 24, b: 37 },
                hsl: Hsl { h: 240.0, s: 0.2131147540983607, l: 0.11960784313725492 },
            },
            crust: Color {
                name: "crust",
                accent: false,
                hex: "#11111b",
                rgb: Rgb { r: 17, g: 17, b: 27 },
                hsl: Hsl { h: 240.0, s: 0.2272727272727273, l: 0.08627450980392157 },
            },
        },
    },
};
