// DO NOT MODIFY THIS FILE!
// The contents of this file are generated by build.rs automatically.
// Any changes you make here WILL be overwritten.
#![allow(clippy::unreadable_literal)]
use crate::{Color, Flavor, Palette};
pub static PALETTE: Palette = Palette {
    flavors: ::phf::Map {
        key: 8694567506910003252,
        disps: &[(3, 0)],
        entries: &[
            (
                "mocha",
                Flavor {
                    name: "Mocha",
                    dark: true,
                    colors: ::phf::Map {
                        key: 12913932095322966823,
                        disps: &[(3, 0), (0, 10), (3, 18), (2, 14), (13, 20), (2, 8)],
                        entries: &[
                            (
                                "red",
                                Color {
                                    name: "red",
                                    accent: true,
                                    hex: "#f38ba8",
                                    rgb: &[243, 139, 168],
                                    hsl: &[
                                        343.2692307692308,
                                        0.8124999999999998,
                                        0.7490196078431373,
                                    ],
                                },
                            ),
                            (
                                "green",
                                Color {
                                    name: "green",
                                    accent: true,
                                    hex: "#a6e3a1",
                                    rgb: &[166, 227, 161],
                                    hsl: &[
                                        115.45454545454544,
                                        0.5409836065573769,
                                        0.7607843137254902,
                                    ],
                                },
                            ),
                            (
                                "sapphire",
                                Color {
                                    name: "sapphire",
                                    accent: true,
                                    hex: "#74c7ec",
                                    rgb: &[116, 199, 236],
                                    hsl: &[198.5, 0.759493670886076, 0.6901960784313725],
                                },
                            ),
                            (
                                "flamingo",
                                Color {
                                    name: "flamingo",
                                    accent: true,
                                    hex: "#f2cdcd",
                                    rgb: &[242, 205, 205],
                                    hsl: &[0.0, 0.587301587301587, 0.8764705882352941],
                                },
                            ),
                            (
                                "overlay0",
                                Color {
                                    name: "overlay0",
                                    accent: false,
                                    hex: "#6c7086",
                                    rgb: &[108, 112, 134],
                                    hsl: &[
                                        230.7692307692308,
                                        0.10743801652892564,
                                        0.4745098039215686,
                                    ],
                                },
                            ),
                            (
                                "mauve",
                                Color {
                                    name: "mauve",
                                    accent: true,
                                    hex: "#cba6f7",
                                    rgb: &[203, 166, 247],
                                    hsl: &[
                                        267.4074074074074,
                                        0.8350515463917528,
                                        0.8098039215686275,
                                    ],
                                },
                            ),
                            (
                                "blue",
                                Color {
                                    name: "blue",
                                    accent: true,
                                    hex: "#89b4fa",
                                    rgb: &[137, 180, 250],
                                    hsl: &[217.1681415929203, 0.91869918699187, 0.7588235294117647],
                                },
                            ),
                            (
                                "peach",
                                Color {
                                    name: "peach",
                                    accent: true,
                                    hex: "#fab387",
                                    rgb: &[250, 179, 135],
                                    hsl: &[22.95652173913043, 0.92, 0.7549019607843137],
                                },
                            ),
                            (
                                "subtext0",
                                Color {
                                    name: "subtext0",
                                    accent: false,
                                    hex: "#a6adc8",
                                    rgb: &[166, 173, 200],
                                    hsl: &[
                                        227.6470588235294,
                                        0.23611111111111105,
                                        0.7176470588235294,
                                    ],
                                },
                            ),
                            (
                                "sky",
                                Color {
                                    name: "sky",
                                    accent: true,
                                    hex: "#89dceb",
                                    rgb: &[137, 220, 235],
                                    hsl: &[
                                        189.18367346938777,
                                        0.7101449275362316,
                                        0.7294117647058823,
                                    ],
                                },
                            ),
                            (
                                "surface1",
                                Color {
                                    name: "surface1",
                                    accent: false,
                                    hex: "#45475a",
                                    rgb: &[69, 71, 90],
                                    hsl: &[
                                        234.2857142857143,
                                        0.13207547169811326,
                                        0.31176470588235294,
                                    ],
                                },
                            ),
                            (
                                "maroon",
                                Color {
                                    name: "maroon",
                                    accent: true,
                                    hex: "#eba0ac",
                                    rgb: &[235, 160, 172],
                                    hsl: &[350.4, 0.6521739130434779, 0.7745098039215685],
                                },
                            ),
                            (
                                "yellow",
                                Color {
                                    name: "yellow",
                                    accent: true,
                                    hex: "#f9e2af",
                                    rgb: &[249, 226, 175],
                                    hsl: &[
                                        41.35135135135135,
                                        0.8604651162790699,
                                        0.8313725490196078,
                                    ],
                                },
                            ),
                            (
                                "pink",
                                Color {
                                    name: "pink",
                                    accent: true,
                                    hex: "#f5c2e7",
                                    rgb: &[245, 194, 231],
                                    hsl: &[
                                        316.4705882352941,
                                        0.7183098591549301,
                                        0.8607843137254902,
                                    ],
                                },
                            ),
                            (
                                "rosewater",
                                Color {
                                    name: "rosewater",
                                    accent: true,
                                    hex: "#f5e0dc",
                                    rgb: &[245, 224, 220],
                                    hsl: &[9.599999999999968, 0.555555555555556, 0.911764705882353],
                                },
                            ),
                            (
                                "surface0",
                                Color {
                                    name: "surface0",
                                    accent: false,
                                    hex: "#313244",
                                    rgb: &[49, 50, 68],
                                    hsl: &[
                                        236.84210526315792,
                                        0.16239316239316234,
                                        0.22941176470588237,
                                    ],
                                },
                            ),
                            (
                                "text",
                                Color {
                                    name: "text",
                                    accent: false,
                                    hex: "#cdd6f4",
                                    rgb: &[205, 214, 244],
                                    hsl: &[
                                        226.15384615384616,
                                        0.6393442622950825,
                                        0.8803921568627451,
                                    ],
                                },
                            ),
                            (
                                "base",
                                Color {
                                    name: "base",
                                    accent: false,
                                    hex: "#1e1e2e",
                                    rgb: &[30, 30, 46],
                                    hsl: &[240.0, 0.21052631578947367, 0.14901960784313725],
                                },
                            ),
                            (
                                "subtext1",
                                Color {
                                    name: "subtext1",
                                    accent: false,
                                    hex: "#bac2de",
                                    rgb: &[186, 194, 222],
                                    hsl: &[226.66666666666669, 0.35294117647058837, 0.8],
                                },
                            ),
                            (
                                "lavender",
                                Color {
                                    name: "lavender",
                                    accent: true,
                                    hex: "#b4befe",
                                    rgb: &[180, 190, 254],
                                    hsl: &[
                                        231.89189189189187,
                                        0.973684210526316,
                                        0.8509803921568628,
                                    ],
                                },
                            ),
                            (
                                "teal",
                                Color {
                                    name: "teal",
                                    accent: true,
                                    hex: "#94e2d5",
                                    rgb: &[148, 226, 213],
                                    hsl: &[
                                        170.00000000000003,
                                        0.5735294117647057,
                                        0.7333333333333334,
                                    ],
                                },
                            ),
                            (
                                "mantle",
                                Color {
                                    name: "mantle",
                                    accent: false,
                                    hex: "#181825",
                                    rgb: &[24, 24, 37],
                                    hsl: &[240.0, 0.2131147540983607, 0.11960784313725492],
                                },
                            ),
                            (
                                "crust",
                                Color {
                                    name: "crust",
                                    accent: false,
                                    hex: "#11111b",
                                    rgb: &[17, 17, 27],
                                    hsl: &[240.0, 0.2272727272727273, 0.08627450980392157],
                                },
                            ),
                            (
                                "surface2",
                                Color {
                                    name: "surface2",
                                    accent: false,
                                    hex: "#585b70",
                                    rgb: &[88, 91, 112],
                                    hsl: &[232.5, 0.12, 0.392156862745098],
                                },
                            ),
                            (
                                "overlay1",
                                Color {
                                    name: "overlay1",
                                    accent: false,
                                    hex: "#7f849c",
                                    rgb: &[127, 132, 156],
                                    hsl: &[
                                        229.65517241379308,
                                        0.12775330396475776,
                                        0.5549019607843138,
                                    ],
                                },
                            ),
                            (
                                "overlay2",
                                Color {
                                    name: "overlay2",
                                    accent: false,
                                    hex: "#9399b2",
                                    rgb: &[147, 153, 178],
                                    hsl: &[
                                        228.3870967741935,
                                        0.16756756756756758,
                                        0.6372549019607843,
                                    ],
                                },
                            ),
                        ],
                    },
                },
            ),
            (
                "frappe",
                Flavor {
                    name: "Frappé",
                    dark: true,
                    colors: ::phf::Map {
                        key: 12913932095322966823,
                        disps: &[(3, 0), (0, 10), (3, 18), (2, 14), (13, 20), (2, 8)],
                        entries: &[
                            (
                                "red",
                                Color {
                                    name: "red",
                                    accent: true,
                                    hex: "#e78284",
                                    rgb: &[231, 130, 132],
                                    hsl: &[
                                        358.8118811881188,
                                        0.6778523489932885,
                                        0.7078431372549019,
                                    ],
                                },
                            ),
                            (
                                "green",
                                Color {
                                    name: "green",
                                    accent: true,
                                    hex: "#a6d189",
                                    rgb: &[166, 209, 137],
                                    hsl: &[
                                        95.83333333333331,
                                        0.4390243902439024,
                                        0.6784313725490196,
                                    ],
                                },
                            ),
                            (
                                "sapphire",
                                Color {
                                    name: "sapphire",
                                    accent: true,
                                    hex: "#85c1dc",
                                    rgb: &[133, 193, 220],
                                    hsl: &[
                                        198.62068965517244,
                                        0.5541401273885351,
                                        0.692156862745098,
                                    ],
                                },
                            ),
                            (
                                "flamingo",
                                Color {
                                    name: "flamingo",
                                    accent: true,
                                    hex: "#eebebe",
                                    rgb: &[238, 190, 190],
                                    hsl: &[0.0, 0.5853658536585367, 0.8392156862745098],
                                },
                            ),
                            (
                                "overlay0",
                                Color {
                                    name: "overlay0",
                                    accent: false,
                                    hex: "#737994",
                                    rgb: &[115, 121, 148],
                                    hsl: &[
                                        229.0909090909091,
                                        0.13360323886639683,
                                        0.515686274509804,
                                    ],
                                },
                            ),
                            (
                                "mauve",
                                Color {
                                    name: "mauve",
                                    accent: true,
                                    hex: "#ca9ee6",
                                    rgb: &[202, 158, 230],
                                    hsl: &[
                                        276.66666666666663,
                                        0.5901639344262294,
                                        0.7607843137254902,
                                    ],
                                },
                            ),
                            (
                                "blue",
                                Color {
                                    name: "blue",
                                    accent: true,
                                    hex: "#8caaee",
                                    rgb: &[140, 170, 238],
                                    hsl: &[
                                        221.6326530612245,
                                        0.7424242424242424,
                                        0.7411764705882353,
                                    ],
                                },
                            ),
                            (
                                "peach",
                                Color {
                                    name: "peach",
                                    accent: true,
                                    hex: "#ef9f76",
                                    rgb: &[239, 159, 118],
                                    hsl: &[20.33057851239669, 0.7908496732026143, 0.7],
                                },
                            ),
                            (
                                "subtext0",
                                Color {
                                    name: "subtext0",
                                    accent: false,
                                    hex: "#a5adce",
                                    rgb: &[165, 173, 206],
                                    hsl: &[
                                        228.2926829268293,
                                        0.2949640287769784,
                                        0.7274509803921569,
                                    ],
                                },
                            ),
                            (
                                "sky",
                                Color {
                                    name: "sky",
                                    accent: true,
                                    hex: "#99d1db",
                                    rgb: &[153, 209, 219],
                                    hsl: &[
                                        189.0909090909091,
                                        0.47826086956521735,
                                        0.7294117647058823,
                                    ],
                                },
                            ),
                            (
                                "surface1",
                                Color {
                                    name: "surface1",
                                    accent: false,
                                    hex: "#51576d",
                                    rgb: &[81, 87, 109],
                                    hsl: &[
                                        227.1428571428571,
                                        0.14736842105263157,
                                        0.37254901960784315,
                                    ],
                                },
                            ),
                            (
                                "maroon",
                                Color {
                                    name: "maroon",
                                    accent: true,
                                    hex: "#ea999c",
                                    rgb: &[234, 153, 156],
                                    hsl: &[
                                        357.77777777777777,
                                        0.6585365853658534,
                                        0.7588235294117647,
                                    ],
                                },
                            ),
                            (
                                "yellow",
                                Color {
                                    name: "yellow",
                                    accent: true,
                                    hex: "#e5c890",
                                    rgb: &[229, 200, 144],
                                    hsl: &[
                                        39.52941176470588,
                                        0.6204379562043796,
                                        0.7313725490196079,
                                    ],
                                },
                            ),
                            (
                                "pink",
                                Color {
                                    name: "pink",
                                    accent: true,
                                    hex: "#f4b8e4",
                                    rgb: &[244, 184, 228],
                                    hsl: &[316.0, 0.7317073170731713, 0.8392156862745098],
                                },
                            ),
                            (
                                "rosewater",
                                Color {
                                    name: "rosewater",
                                    accent: true,
                                    hex: "#f2d5cf",
                                    rgb: &[242, 213, 207],
                                    hsl: &[
                                        10.2857142857143,
                                        0.5737704918032784,
                                        0.8803921568627451,
                                    ],
                                },
                            ),
                            (
                                "surface0",
                                Color {
                                    name: "surface0",
                                    accent: false,
                                    hex: "#414559",
                                    rgb: &[65, 69, 89],
                                    hsl: &[
                                        230.00000000000003,
                                        0.15584415584415584,
                                        0.30196078431372547,
                                    ],
                                },
                            ),
                            (
                                "text",
                                Color {
                                    name: "text",
                                    accent: false,
                                    hex: "#c6d0f5",
                                    rgb: &[198, 208, 245],
                                    hsl: &[
                                        227.2340425531915,
                                        0.7014925373134333,
                                        0.8686274509803922,
                                    ],
                                },
                            ),
                            (
                                "base",
                                Color {
                                    name: "base",
                                    accent: false,
                                    hex: "#303446",
                                    rgb: &[48, 52, 70],
                                    hsl: &[
                                        229.0909090909091,
                                        0.18644067796610175,
                                        0.23137254901960785,
                                    ],
                                },
                            ),
                            (
                                "subtext1",
                                Color {
                                    name: "subtext1",
                                    accent: false,
                                    hex: "#b5bfe2",
                                    rgb: &[181, 191, 226],
                                    hsl: &[
                                        226.66666666666669,
                                        0.43689320388349495,
                                        0.7980392156862746,
                                    ],
                                },
                            ),
                            (
                                "lavender",
                                Color {
                                    name: "lavender",
                                    accent: true,
                                    hex: "#babbf1",
                                    rgb: &[186, 187, 241],
                                    hsl: &[
                                        238.9090909090909,
                                        0.6626506024096385,
                                        0.8372549019607842,
                                    ],
                                },
                            ),
                            (
                                "teal",
                                Color {
                                    name: "teal",
                                    accent: true,
                                    hex: "#81c8be",
                                    rgb: &[129, 200, 190],
                                    hsl: &[
                                        171.5492957746479,
                                        0.3922651933701657,
                                        0.6450980392156862,
                                    ],
                                },
                            ),
                            (
                                "mantle",
                                Color {
                                    name: "mantle",
                                    accent: false,
                                    hex: "#292c3c",
                                    rgb: &[41, 44, 60],
                                    hsl: &[
                                        230.52631578947367,
                                        0.1881188118811881,
                                        0.19803921568627453,
                                    ],
                                },
                            ),
                            (
                                "crust",
                                Color {
                                    name: "crust",
                                    accent: false,
                                    hex: "#232634",
                                    rgb: &[35, 38, 52],
                                    hsl: &[
                                        229.4117647058824,
                                        0.19540229885057467,
                                        0.17058823529411765,
                                    ],
                                },
                            ),
                            (
                                "surface2",
                                Color {
                                    name: "surface2",
                                    accent: false,
                                    hex: "#626880",
                                    rgb: &[98, 104, 128],
                                    hsl: &[
                                        228.00000000000003,
                                        0.1327433628318584,
                                        0.4431372549019608,
                                    ],
                                },
                            ),
                            (
                                "overlay1",
                                Color {
                                    name: "overlay1",
                                    accent: false,
                                    hex: "#838ba7",
                                    rgb: &[131, 139, 167],
                                    hsl: &[
                                        226.66666666666669,
                                        0.16981132075471703,
                                        0.584313725490196,
                                    ],
                                },
                            ),
                            (
                                "overlay2",
                                Color {
                                    name: "overlay2",
                                    accent: false,
                                    hex: "#949cbb",
                                    rgb: &[148, 156, 187],
                                    hsl: &[
                                        227.69230769230768,
                                        0.22285714285714275,
                                        0.6568627450980392,
                                    ],
                                },
                            ),
                        ],
                    },
                },
            ),
            (
                "macchiato",
                Flavor {
                    name: "Macchiato",
                    dark: true,
                    colors: ::phf::Map {
                        key: 12913932095322966823,
                        disps: &[(3, 0), (0, 10), (3, 18), (2, 14), (13, 20), (2, 8)],
                        entries: &[
                            (
                                "red",
                                Color {
                                    name: "red",
                                    accent: true,
                                    hex: "#ed8796",
                                    rgb: &[237, 135, 150],
                                    hsl: &[
                                        351.1764705882353,
                                        0.7391304347826088,
                                        0.7294117647058824,
                                    ],
                                },
                            ),
                            (
                                "green",
                                Color {
                                    name: "green",
                                    accent: true,
                                    hex: "#a6da95",
                                    rgb: &[166, 218, 149],
                                    hsl: &[
                                        105.21739130434784,
                                        0.4825174825174825,
                                        0.7196078431372549,
                                    ],
                                },
                            ),
                            (
                                "sapphire",
                                Color {
                                    name: "sapphire",
                                    accent: true,
                                    hex: "#7dc4e4",
                                    rgb: &[125, 196, 228],
                                    hsl: &[
                                        198.64077669902912,
                                        0.6560509554140128,
                                        0.692156862745098,
                                    ],
                                },
                            ),
                            (
                                "flamingo",
                                Color {
                                    name: "flamingo",
                                    accent: true,
                                    hex: "#f0c6c6",
                                    rgb: &[240, 198, 198],
                                    hsl: &[0.0, 0.5833333333333333, 0.8588235294117648],
                                },
                            ),
                            (
                                "overlay0",
                                Color {
                                    name: "overlay0",
                                    accent: false,
                                    hex: "#6e738d",
                                    rgb: &[110, 115, 141],
                                    hsl: &[
                                        230.32258064516128,
                                        0.12350597609561752,
                                        0.49215686274509807,
                                    ],
                                },
                            ),
                            (
                                "mauve",
                                Color {
                                    name: "mauve",
                                    accent: true,
                                    hex: "#c6a0f6",
                                    rgb: &[198, 160, 246],
                                    hsl: &[
                                        266.51162790697674,
                                        0.8269230769230772,
                                        0.7960784313725491,
                                    ],
                                },
                            ),
                            (
                                "blue",
                                Color {
                                    name: "blue",
                                    accent: true,
                                    hex: "#8aadf4",
                                    rgb: &[138, 173, 244],
                                    hsl: &[
                                        220.188679245283,
                                        0.8281250000000003,
                                        0.7490196078431373,
                                    ],
                                },
                            ),
                            (
                                "peach",
                                Color {
                                    name: "peach",
                                    accent: true,
                                    hex: "#f5a97f",
                                    rgb: &[245, 169, 127],
                                    hsl: &[
                                        21.355932203389827,
                                        0.8550724637681162,
                                        0.7294117647058824,
                                    ],
                                },
                            ),
                            (
                                "subtext0",
                                Color {
                                    name: "subtext0",
                                    accent: false,
                                    hex: "#a5adcb",
                                    rgb: &[165, 173, 203],
                                    hsl: &[
                                        227.36842105263156,
                                        0.2676056338028167,
                                        0.7215686274509804,
                                    ],
                                },
                            ),
                            (
                                "sky",
                                Color {
                                    name: "sky",
                                    accent: true,
                                    hex: "#91d7e3",
                                    rgb: &[145, 215, 227],
                                    hsl: &[
                                        188.780487804878,
                                        0.5942028985507245,
                                        0.7294117647058823,
                                    ],
                                },
                            ),
                            (
                                "surface1",
                                Color {
                                    name: "surface1",
                                    accent: false,
                                    hex: "#494d64",
                                    rgb: &[73, 77, 100],
                                    hsl: &[
                                        231.11111111111111,
                                        0.15606936416184972,
                                        0.3392156862745098,
                                    ],
                                },
                            ),
                            (
                                "maroon",
                                Color {
                                    name: "maroon",
                                    accent: true,
                                    hex: "#ee99a0",
                                    rgb: &[238, 153, 160],
                                    hsl: &[
                                        355.05882352941177,
                                        0.7142857142857143,
                                        0.7666666666666666,
                                    ],
                                },
                            ),
                            (
                                "yellow",
                                Color {
                                    name: "yellow",
                                    accent: true,
                                    hex: "#eed49f",
                                    rgb: &[238, 212, 159],
                                    hsl: &[
                                        40.253164556962034,
                                        0.6991150442477877,
                                        0.7784313725490196,
                                    ],
                                },
                            ),
                            (
                                "pink",
                                Color {
                                    name: "pink",
                                    accent: true,
                                    hex: "#f5bde6",
                                    rgb: &[245, 189, 230],
                                    hsl: &[
                                        316.0714285714286,
                                        0.7368421052631583,
                                        0.8509803921568628,
                                    ],
                                },
                            ),
                            (
                                "rosewater",
                                Color {
                                    name: "rosewater",
                                    accent: true,
                                    hex: "#f4dbd6",
                                    rgb: &[244, 219, 214],
                                    hsl: &[
                                        9.999999999999964,
                                        0.5769230769230775,
                                        0.8980392156862745,
                                    ],
                                },
                            ),
                            (
                                "surface0",
                                Color {
                                    name: "surface0",
                                    accent: false,
                                    hex: "#363a4f",
                                    rgb: &[54, 58, 79],
                                    hsl: &[230.4, 0.1879699248120301, 0.2607843137254902],
                                },
                            ),
                            (
                                "text",
                                Color {
                                    name: "text",
                                    accent: false,
                                    hex: "#cad3f5",
                                    rgb: &[202, 211, 245],
                                    hsl: &[
                                        227.4418604651163,
                                        0.6825396825396831,
                                        0.8764705882352941,
                                    ],
                                },
                            ),
                            (
                                "base",
                                Color {
                                    name: "base",
                                    accent: false,
                                    hex: "#24273a",
                                    rgb: &[36, 39, 58],
                                    hsl: &[
                                        231.8181818181818,
                                        0.23404255319148937,
                                        0.1843137254901961,
                                    ],
                                },
                            ),
                            (
                                "subtext1",
                                Color {
                                    name: "subtext1",
                                    accent: false,
                                    hex: "#b8c0e0",
                                    rgb: &[184, 192, 224],
                                    hsl: &[228.0, 0.392156862745098, 0.8],
                                },
                            ),
                            (
                                "lavender",
                                Color {
                                    name: "lavender",
                                    accent: true,
                                    hex: "#b7bdf8",
                                    rgb: &[183, 189, 248],
                                    hsl: &[
                                        234.46153846153848,
                                        0.8227848101265824,
                                        0.8450980392156863,
                                    ],
                                },
                            ),
                            (
                                "teal",
                                Color {
                                    name: "teal",
                                    accent: true,
                                    hex: "#8bd5ca",
                                    rgb: &[139, 213, 202],
                                    hsl: &[
                                        171.08108108108107,
                                        0.46835443037974706,
                                        0.6901960784313725,
                                    ],
                                },
                            ),
                            (
                                "mantle",
                                Color {
                                    name: "mantle",
                                    accent: false,
                                    hex: "#1e2030",
                                    rgb: &[30, 32, 48],
                                    hsl: &[
                                        233.33333333333337,
                                        0.23076923076923075,
                                        0.15294117647058825,
                                    ],
                                },
                            ),
                            (
                                "crust",
                                Color {
                                    name: "crust",
                                    accent: false,
                                    hex: "#181926",
                                    rgb: &[24, 25, 38],
                                    hsl: &[
                                        235.71428571428572,
                                        0.2258064516129032,
                                        0.1215686274509804,
                                    ],
                                },
                            ),
                            (
                                "surface2",
                                Color {
                                    name: "surface2",
                                    accent: false,
                                    hex: "#5b6078",
                                    rgb: &[91, 96, 120],
                                    hsl: &[
                                        229.65517241379308,
                                        0.1374407582938389,
                                        0.4137254901960784,
                                    ],
                                },
                            ),
                            (
                                "overlay1",
                                Color {
                                    name: "overlay1",
                                    accent: false,
                                    hex: "#8087a2",
                                    rgb: &[128, 135, 162],
                                    hsl: &[
                                        227.6470588235294,
                                        0.1545454545454545,
                                        0.5686274509803921,
                                    ],
                                },
                            ),
                            (
                                "overlay2",
                                Color {
                                    name: "overlay2",
                                    accent: false,
                                    hex: "#939ab7",
                                    rgb: &[147, 154, 183],
                                    hsl: &[
                                        228.33333333333331,
                                        0.2000000000000001,
                                        0.6470588235294117,
                                    ],
                                },
                            ),
                        ],
                    },
                },
            ),
            (
                "latte",
                Flavor {
                    name: "Latte",
                    dark: false,
                    colors: ::phf::Map {
                        key: 12913932095322966823,
                        disps: &[(3, 0), (0, 10), (3, 18), (2, 14), (13, 20), (2, 8)],
                        entries: &[
                            (
                                "red",
                                Color {
                                    name: "red",
                                    accent: true,
                                    hex: "#d20f39",
                                    rgb: &[210, 15, 57],
                                    hsl: &[
                                        347.0769230769231,
                                        0.8666666666666666,
                                        0.4411764705882353,
                                    ],
                                },
                            ),
                            (
                                "green",
                                Color {
                                    name: "green",
                                    accent: true,
                                    hex: "#40a02b",
                                    rgb: &[64, 160, 43],
                                    hsl: &[
                                        109.23076923076924,
                                        0.5763546798029556,
                                        0.39803921568627454,
                                    ],
                                },
                            ),
                            (
                                "sapphire",
                                Color {
                                    name: "sapphire",
                                    accent: true,
                                    hex: "#209fb5",
                                    rgb: &[32, 159, 181],
                                    hsl: &[
                                        188.85906040268455,
                                        0.6995305164319249,
                                        0.4176470588235294,
                                    ],
                                },
                            ),
                            (
                                "flamingo",
                                Color {
                                    name: "flamingo",
                                    accent: true,
                                    hex: "#dd7878",
                                    rgb: &[221, 120, 120],
                                    hsl: &[0.0, 0.5976331360946746, 0.6686274509803922],
                                },
                            ),
                            (
                                "overlay0",
                                Color {
                                    name: "overlay0",
                                    accent: false,
                                    hex: "#9ca0b0",
                                    rgb: &[156, 160, 176],
                                    hsl: &[
                                        228.00000000000003,
                                        0.11235955056179768,
                                        0.6509803921568628,
                                    ],
                                },
                            ),
                            (
                                "mauve",
                                Color {
                                    name: "mauve",
                                    accent: true,
                                    hex: "#8839ef",
                                    rgb: &[136, 57, 239],
                                    hsl: &[
                                        266.0439560439561,
                                        0.8504672897196262,
                                        0.5803921568627451,
                                    ],
                                },
                            ),
                            (
                                "blue",
                                Color {
                                    name: "blue",
                                    accent: true,
                                    hex: "#1e66f5",
                                    rgb: &[30, 102, 245],
                                    hsl: &[
                                        219.90697674418607,
                                        0.9148936170212768,
                                        0.5392156862745098,
                                    ],
                                },
                            ),
                            (
                                "peach",
                                Color {
                                    name: "peach",
                                    accent: true,
                                    hex: "#fe640b",
                                    rgb: &[254, 100, 11],
                                    hsl: &[
                                        21.975308641975307,
                                        0.9918367346938776,
                                        0.5196078431372549,
                                    ],
                                },
                            ),
                            (
                                "subtext0",
                                Color {
                                    name: "subtext0",
                                    accent: false,
                                    hex: "#6c6f85",
                                    rgb: &[108, 111, 133],
                                    hsl: &[232.8, 0.10373443983402494, 0.4725490196078431],
                                },
                            ),
                            (
                                "sky",
                                Color {
                                    name: "sky",
                                    accent: true,
                                    hex: "#04a5e5",
                                    rgb: &[4, 165, 229],
                                    hsl: &[
                                        197.0666666666667,
                                        0.965665236051502,
                                        0.45686274509803926,
                                    ],
                                },
                            ),
                            (
                                "surface1",
                                Color {
                                    name: "surface1",
                                    accent: false,
                                    hex: "#bcc0cc",
                                    rgb: &[188, 192, 204],
                                    hsl: &[
                                        225.00000000000003,
                                        0.13559322033898308,
                                        0.7686274509803922,
                                    ],
                                },
                            ),
                            (
                                "maroon",
                                Color {
                                    name: "maroon",
                                    accent: true,
                                    hex: "#e64553",
                                    rgb: &[230, 69, 83],
                                    hsl: &[
                                        354.78260869565213,
                                        0.76303317535545,
                                        0.5862745098039216,
                                    ],
                                },
                            ),
                            (
                                "yellow",
                                Color {
                                    name: "yellow",
                                    accent: true,
                                    hex: "#df8e1d",
                                    rgb: &[223, 142, 29],
                                    hsl: &[
                                        34.948453608247426,
                                        0.7698412698412698,
                                        0.4941176470588235,
                                    ],
                                },
                            ),
                            (
                                "pink",
                                Color {
                                    name: "pink",
                                    accent: true,
                                    hex: "#ea76cb",
                                    rgb: &[234, 118, 203],
                                    hsl: &[
                                        316.0344827586207,
                                        0.7341772151898731,
                                        0.6901960784313725,
                                    ],
                                },
                            ),
                            (
                                "rosewater",
                                Color {
                                    name: "rosewater",
                                    accent: true,
                                    hex: "#dc8a78",
                                    rgb: &[220, 138, 120],
                                    hsl: &[
                                        10.799999999999995,
                                        0.5882352941176472,
                                        0.6666666666666667,
                                    ],
                                },
                            ),
                            (
                                "surface0",
                                Color {
                                    name: "surface0",
                                    accent: false,
                                    hex: "#ccd0da",
                                    rgb: &[204, 208, 218],
                                    hsl: &[
                                        222.85714285714292,
                                        0.1590909090909089,
                                        0.8274509803921568,
                                    ],
                                },
                            ),
                            (
                                "text",
                                Color {
                                    name: "text",
                                    accent: false,
                                    hex: "#4c4f69",
                                    rgb: &[76, 79, 105],
                                    hsl: &[
                                        233.79310344827587,
                                        0.16022099447513813,
                                        0.3549019607843137,
                                    ],
                                },
                            ),
                            (
                                "base",
                                Color {
                                    name: "base",
                                    accent: false,
                                    hex: "#eff1f5",
                                    rgb: &[239, 241, 245],
                                    hsl: &[
                                        220.00000000000009,
                                        0.23076923076923136,
                                        0.9490196078431372,
                                    ],
                                },
                            ),
                            (
                                "subtext1",
                                Color {
                                    name: "subtext1",
                                    accent: false,
                                    hex: "#5c5f77",
                                    rgb: &[92, 95, 119],
                                    hsl: &[
                                        233.33333333333337,
                                        0.1279620853080569,
                                        0.4137254901960784,
                                    ],
                                },
                            ),
                            (
                                "lavender",
                                Color {
                                    name: "lavender",
                                    accent: true,
                                    hex: "#7287fd",
                                    rgb: &[114, 135, 253],
                                    hsl: &[
                                        230.93525179856115,
                                        0.972027972027972,
                                        0.7196078431372549,
                                    ],
                                },
                            ),
                            (
                                "teal",
                                Color {
                                    name: "teal",
                                    accent: true,
                                    hex: "#179299",
                                    rgb: &[23, 146, 153],
                                    hsl: &[
                                        183.23076923076923,
                                        0.7386363636363636,
                                        0.34509803921568627,
                                    ],
                                },
                            ),
                            (
                                "mantle",
                                Color {
                                    name: "mantle",
                                    accent: false,
                                    hex: "#e6e9ef",
                                    rgb: &[230, 233, 239],
                                    hsl: &[
                                        220.00000000000009,
                                        0.21951219512195116,
                                        0.919607843137255,
                                    ],
                                },
                            ),
                            (
                                "crust",
                                Color {
                                    name: "crust",
                                    accent: false,
                                    hex: "#dce0e8",
                                    rgb: &[220, 224, 232],
                                    hsl: &[
                                        220.00000000000009,
                                        0.2068965517241376,
                                        0.8862745098039215,
                                    ],
                                },
                            ),
                            (
                                "surface2",
                                Color {
                                    name: "surface2",
                                    accent: false,
                                    hex: "#acb0be",
                                    rgb: &[172, 176, 190],
                                    hsl: &[
                                        226.6666666666667,
                                        0.1216216216216216,
                                        0.7098039215686275,
                                    ],
                                },
                            ),
                            (
                                "overlay1",
                                Color {
                                    name: "overlay1",
                                    accent: false,
                                    hex: "#8c8fa1",
                                    rgb: &[140, 143, 161],
                                    hsl: &[
                                        231.42857142857144,
                                        0.10047846889952144,
                                        0.5901960784313726,
                                    ],
                                },
                            ),
                            (
                                "overlay2",
                                Color {
                                    name: "overlay2",
                                    accent: false,
                                    hex: "#7c7f93",
                                    rgb: &[124, 127, 147],
                                    hsl: &[
                                        232.17391304347825,
                                        0.09623430962343092,
                                        0.5313725490196078,
                                    ],
                                },
                            ),
                        ],
                    },
                },
            ),
        ],
    },
};
